services:
  - postgres:latest
variables:
  POSTGRES_DB: agendadorAPI_test
  POSTGRES_USER: agendador
  POSTGRES_PASSWORD: 123mudar
  POSTGRES_HOST: postgres
  AGENDADOR_URL: 'marula.c3sl.ufpr.br:5000/c3sl/agendador-backend'
  GIT_SUBMODULE_STRATEGY: recursive
stages:
  - test
  - build
  - deploy

test:
  stage: test
  
  before_script:
    - apt-get update -y
    - apt-get install default-jre postgresql-client -y
    # official way to provide password to psql: http://www.postgresql.org/docs/9.3/static/libpq-envars.html
    - export PGPASSWORD=$POSTGRES_PASSWORD
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT 'OK' AS status;"
    # gems
    - gem install bundler
    - bundle install --jobs $(nproc) --path=/cache/bundler

  script:
    - bundle exec rake db:migrate:reset RAILS_ENV=test
    - rake test
  tags:
    - ruby
    - postgres

build:
    stage: build
    script:
        - docker build -t ${AGENDADOR_URL}:${CI_COMMIT_REF_NAME} .
    tags:
        - docker
        - build

deploy:
    stage: deploy
    script:
        - docker push ${AGENDADOR_URL}:${CI_COMMIT_REF_NAME}
    tags:
        - docker
        - build
    only:
        - testing
        - master
