version: "3" # version matters, see https://docs.docker.com/compose/networking/
services:
    agendador-postgres:
        container_name: agendador-postgres
        image: postgres:9.6
        environment:
            POSTGRES_USER: ${AGENDADOR_API_DB_USER}
            POSTGRES_PASSWORD: ${AGENDADOR_API_DB_PASSWORD}
        volumes:
            - /var/lib/postgresql/data:/var/lib/postgresql/data
        networks:
            backend:

    agendador-redis:
        image: redis:3.2
        command: redis-server --requirepass ${AGENDADOR_REDIS_PASSWORD}
        volumes:
            - /var/redis/data:/redis/data
        networks:
            backend:

    agendador-backend:
        image: marula.c3sl.ufpr.br:5000/c3sl/agendador-backend:latest
        build: .
        volumes:
#Uncomment the environment below
#Develop
            - .:/app/
#Production
    #        - /root/back-end/images/citizens:/app/images/citizens
    #        - /root/back-end/images/city_halls:/app/images/city_halls
    #        - /root/back-end/data/citizen_upload:/app/data/citizen_upload
        environment:
            RAILS_ENV: ${AGENDADOR_RAILS_ENV}
            AGENDADOR_REDIS_PASSWORD: ${AGENDADOR_REDIS_PASSWORD}
            AGENDADOR_API_DB_PASSWORD: ${AGENDADOR_API_DB_PASSWORD}
            AGENDADOR_API_DB_USER: ${AGENDADOR_API_DB_USER}
            SECRET_KEY_BASE: ${AGENDADOR_SECRET_KEY_BASE}
            PGHOST: agendador-postgres
            REDISHOST: agendador-redis
            MAIL_USERNAME: ${MAIL_USERNAME}
            MAIL_PASSWORD: ${MAIL_PASSWORD}
        ports:
            - '3000:3000'
        depends_on:
            - agendador-postgres
            - agendador-redis
        networks:
            backend:

networks:
    backend:
