agendador-postgres:
  image: postgres:9.6
  environment:
    POSTGRES_USER: agendador
    POSTGRES_PASSWORD: 123mudar
  ports:
    - '5432:5432'

agendador-backend:
  build: .
  volumes:
    - .:/app/
  environment:
     # PGHOST: ${HOSTNAME}
   # PGHOST: ${hostname}
    PGHOST: bojack
  ports:
    - '3000:3000'
     # depends_on:
     #    - 'agendador-postgres'
