version: "3" # version matters, see https://docs.docker.com/compose/networking/
networks:
  backend:
services:
  agendador-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: agendador
      POSTGRES_PASSWORD: 123mudar
    networks:
            backend:

  agendador-redis:
    image: redis:3.2
    command: redis-server --requirepass ${AGENDADOR_REDIS_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - '/redis/data'
    networks:
      backend:

  agendador-backend:
    build: .
    volumes:
      - .:/app/
    environment:
      PGHOST: agendador-postgres
      REDISHOST: agendador-redis
      AGENDADOR_REDIS_PASSWORD: ${AGENDADOR_REDIS_PASSWORD}
    ports:
      - '3000:3000'
    depends_on:
      - agendador-postgres
      - agendador-redis
    networks:
      backend:
