version: "3" # version matters, see https://docs.docker.com/compose/networking/
networks:
  backend:
services:
  agendador-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: agendador
      POSTGRES_PASSWORD: 123mudar
    networks:
            backend:

  agendador-backend:
    build: .
    volumes:
      - .:/app/
    environment:
      PGHOST: agendador-postgres
    ports:
      - '3000:3000'
    depends_on:
      - agendador-postgres
    networks:
      backend:
