class CityHallSerializer < ActiveModel::Serializer
  attributes :id, 
    :active, 
    :address_complement, 
    :address_number, 
    :address_street, 
    :block_text, 
    :citizen_access, 
    :citizen_register, 
    :cep, 
    :description, 
    :email, 
    :logo_content_type, 
    :logo_file_name, 
    :logo_file_size, 
    :logo_updated_at, 
    :name, 
    :neighborhood, 
    :phone1, 
    :phone2, 
    :schedule_period, 
    :show_professional, 
    :support_email, 
    :url
  belongs_to :city
end
