# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: agendadorAPI_development
  username: agendador
  password: 123mudar

test:
  <<: *default
  database: agendadorAPI_test
  username: <%= ENV['AGENDADOR_API_DB_USER'] %>
  password: <%= ENV['AGENDADOR_API_DB_PASSWORD'] %>
  # host: <%= ENV['POSTGRES_HOST'] %>

# You can use this database configuration with:
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
production:
  <<: *default
  database: agendadorAPI_production
  username: <%= ENV['AGENDADOR_API_DB_USER'] %>
  password: <%= ENV['AGENDADOR_API_DB_PASSWORD'] %>
